# Site settings
title: 'DDRop'
subtitle: 'Active Memory Interposer Attacks on Confidential VMs by Dropping DDR5 Writes'

repository: "ddropattack/ddrop"
url: "https://ddropattack.eu"

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

#My Customizations
has_logo: true
paper_logo: assets/images/logo.svg

has_videos_link: true
has_paper_link: true
#Just the name of the file
paper_link: ddrop.pdf
has_slide_link: false
#Just the name of the file
slide_link:

deployment: github

exclude:
  - serve.sh
  - Gemfile
  - Gemfile.lock
